config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    root to: 'layout#index'
    resources :articles, except: :show
    resources :courses, except: :show
    resources :tournaments
    resources :tutorials
  end

  resources :articles, only: [:index, :show] do
    resources :comentarios
  end
  resources :courses, only: [:index, :show]
  resources :tournaments, only: :index
  resources :tutorials, only: :index do
    member do
      put "upvote" => "tutorials#upvote"
      put "downvote" => "tutorials#downvote"
    end
  end


  root to: 'articles#index'
  get '/watch-twitch' => 'tournaments#watch'
  get '/auth/:provider/callback' => 'sessions#create'
  get '/signout' => 'sessions#destroy', :as => :signout
end

app/models/tournament.rb
class Tournament < ActiveRecord::Base
  mount_uploader :image, ImageUploader
  has_many :teams, dependent: :destroy
end

app/controllers/admin/tournaments_controller.rb
class Admin::TournamentsController < ApplicationController
  respond_to :html
  before_action :is_admin

  def index
    @tournaments = Tournament.all.order(created_at: :desc).paginate(:page => params[:page], :per_page => 10)
  end

  def new
    @tournament = Tournament.new
    tournament_status
  end

  def create
    @tournament = Tournament.new(permited_params)
    if @tournament.save
      flash[:notice] = "Torneo creado."
      redirect_to admin_tournaments_path
    else
      respond_with @tournament
    end
  end

  def edit
    @tournament = Tournament.find(params[:id])
    @teams = @tournament.teams.order(:name)
    tournament_status
  end

  def update
    @tournament = Tournament.find(params[:id])
    if @tournament.update(permited_params)
      flash[:notice] = "Torneo actualizado."
      redirect_to admin_tournaments_path
    else
      respond_with @tournament
    end
  end

  def destroy
    @tournament = Tournament.find(params[:id])
    @tournament.destroy
    redirect_to admin_tournaments_path
  end

  private
  def permited_params
    params.require(:tournament).permit(:name, :winner, :image, :status)
  end
  def tournament_status
    @tournament_status = [ "Inscripciones abiertas", "Inscripciones cerradas",
      "Finalizado" ]
  end
end

app/controllers/tournaments_controller.rb
class TournamentsController < ApplicationController
  def index
    @tournaments = Tournament.all.order(created_at: :desc).paginate(:page => params[:page], :per_page => 10)
  end

  def watch
  end
end

app/views/admin/tournaments/_form.html.erb
<%= simple_form_for [:admin, @tournament] do |f| %>
  <%= f.input :name, label: "Nombre" %>
  <% if params[:action] == "edit" %>
    <%= f.input :winner, :collection => @teams,:label_method => :name,:value_method => :id,:label => "Ganador" ,:include_blank => true %>
  <% end %>
  <%= f.input :status,  collection: @tournament_status,
        as: :select, group_method: :status %>
  <%= f.input :image, label: "Imagen",
                      hint: "Agrega una imagen relacionada a la noticia" %>
  <%= f.submit %>
<% end %>

app/views/admin/tournaments/edit.html.erb
<%= render 'form' %>

app/views/admin/tournaments/index.html.erb
<div class="tournament-header">
  <h3>Torneos</h3>
  <%= link_to "Crear torneo", new_admin_tournament_path,
    class: "btn btn-primary" %>
</div>

<div class="tournaments">
  <% @tournaments.each do |tournament| %>
    <div class="tournament">
      <%= image_tag tournament.image %>
      <h3><%= tournament.name %></h3>
      <p> <b>Equipo ganador:</b> <%= tournament.winner %></p>
      <p> <%= tournament.status %> </p>
      <div class="more">
        <%= link_to "Editar", edit_admin_tournament_path(tournament),
          class: "glyphicon glyphicon-edit" %>
        <%= link_to [:admin, tournament], method: :delete, data: { confirm: 'Borrar?' } do %>
          <span class="glyphicon glyphicon-trash"></span>
          Borrar
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/admin/tournaments/new.html.erb
<%= render 'form' %>